apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-custom-nginx
  template:
    metadata:
      labels:
        app: my-custom-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-index-volume
        configMap:
          name: nginx-index
