apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend-app
        imagePullPolicy: IfNotPresent # 로컬 이미지를 사용하도록 설정
        ports:
        - containerPort: 5000
        env:
        - name: OCR_SERVICE_URL
          value: "http://ocr-service:5001" # K8s Service 이름으로 통신
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort # 외부에서 접속 가능하도록 NodePort 타입 사용
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-deployment
spec:
  replicas: 2 # OCR 작업은 오래 걸리므로 2대를 띄워둠
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
      - name: ocr
        image: ocr-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        env:
        - name: TRANSLATE_SERVICE_URL
          value: "http://translate-service:5002"
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-service
spec:
  type: ClusterIP # 클러스터 내부에서만 통신
  selector:
    app: ocr
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translate-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translate
  template:
    metadata:
      labels:
        app: translate
    spec:
      containers:
      - name: translate
        image: translate-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: translate-service
spec:
  type: ClusterIP
  selector:
    app: translate
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002

